import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Tab } from '@headlessui/react'
import Masonry from 'react-masonry-css'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })
const tabs = [
  {
    key: 'all',
    display: 'All'
  },
  {
    key:'oceans',
    display:'Oceans'
  },
  {
    key: 'cities',
    display:'Cities'
  }
];
export default function Home() {
  return (
    <div className="h-full bg-top bg-cover overflow-auto"
    style={{backgroundImage: "url('/photography-bg.png')"}}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <header className="fixed bg-stone-900 bg-opacity-80 top-0 w-full z-10 flex justify-between items-center h-[50px] px-10">
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <div className="text-transparent">hm</div> */}
        <div className='text-center'>Photography Protfolio</div>
        <Link href="#" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">Get in touch</Link>
      </header>
      <main className='pt-[60px]'>
        <div className='flex flex-col items-center'>
          <Tab.Group>
          <Tab.List className="flex items-center gap-8">
            {tabs.map(tab => (
                          <Tab key={tab.key} className="p-4">
                          {({selected}) => (
                             <span className={classNames("uppercase",selected ? "text-white" : "text-stone-600")}>
                              {tab.display}
                              </span>
                          )
                          }
                        </Tab>
            ))}
          </Tab.List>
          <Tab.Panels className="h-[1700px] bg-stone-900 bg-opacity-20 max-w-[800px] w-full p-2 sm:p-4 my-6">
            <Tab.Panel >
              <Masonry breakpointCols={2} className='flex gap-2' columnClassName=''>
                <img src='/city-1.png' alt='city-1' className='my-2'/>
                <img src='/city-2.png' alt='city-2' className='my-2'/>
                <img src='/city-3.png' alt='city-3' className='my-2'/>
                <img src='/city-4.png' alt='city-4' className='my-2'/>
                <img src='/city-5.png' alt='city-5' className='my-2'/>
              </Masonry>
            </Tab.Panel>
            <Tab.Panel>Content 2</Tab.Panel>
            <Tab.Panel>Content 3</Tab.Panel>
          </Tab.Panels>
        </Tab.Group>
      </div>
      </main>
      <footer className='h-[60px] flex justify-center uppercase text-lg font-medium'>
        Photography Protfolio
      </footer>
    </div>
  )
}
